### PR TITLE
Dependabot/npm and yarn/highlight.js 10.1.2

### PR DESCRIPTION
**Pull request by gcusnieux**

### CODE REVIEW

**Comment by gcusnieux** [comment]
Hello @jirutka,

I fix the integration test with the last version of highlight.js. It's okay for you ?

**Comment by gcusnieux** [comment]
🆙 @jirutka

**Comment by jirutka** [comment]
It’s a duplicate of #6 which I merged a moment ago, but thank you anyway!

**Comment by gcusnieux** [comment]
Great ! I did not see ;)

**Pull request closed without merging**
